### ISSUE TITLE
MediaStreamTrack.getSources returning sources with empty labels in recent releases

### ISSUE THREAD

**Issue by brandonecraig** [atom/atom-shell#1017]
We recently upgraded from 0.19.1 to 0.20.6. When pointing to web app that uses MediaStreamTrack.getSources, the sources no longer have the label field populated. For example:

This code is in the web application being served.

```
MediaStreamTrack.getSources (sourceInfos) ->
   i = 0
   while i isnt sourceInfos.length
      console.log "Source #" + i + ": " + sourceInfo.label
```

In the Chrome (version 39.0.2171.95), atom shell (version 0.19.5), and Chromium (version 42.0.2283.0) the console will output something like: 
Input #0: Default
Input #1: Built-in Microphone
Input #2:

But when serving the web app through recent atom shell versions it outputs:
Input #0:
Input #1:
Input #2:

My best guess is this has something to do with permissions to use devices. For example, if I host this code with https, the first time I visit the page in Chrome, the audio inputs will not have labels. After I allow permission to use devices the labels will be populated all subsequent times I visit the page. If I serve the page via http (and not https) then no number of allowing to use devices will populate the labels. As the allow/disallow message does not appear when serving through atom shell I suspect it has something to do with that.

**Comment by brandonecraig** [comment]
I've determined that the issue occurs starting with v0.20.0

**Comment by brandonecraig** [comment]
I've narrowed it down to this span of commits:

# good: [158d8efb8eb2d15c7dad8648daca7fea124ee52c] Merge pull request #910 from sonnyp/patch-1
to
# bad: [654d21100ff2908af6c44e2d2d71ba92b1e96722] Upgrade libchromiumcontent to remove dom storage quota

I can't narrow it down more than that though because when I try to build the project on those commits I experience a failure to checkout submodules. Example:

```
Running in verbose mode
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/brightray'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'

fatal: reference is not a tree: b07fb51bdb232fee33711e3eb48cb56dd3c257e3
fatal: reference is not a tree: f7f439bdd31c901c802108ec903a3bfc0448c3d1
fatal: reference is not a tree: b1d7464f1c05456027d41fa97384765bc1790212
Unable to checkout 'b07fb51bdb232fee33711e3eb48cb56dd3c257e3' in submodule path 'vendor/breakpad'
Unable to checkout 'f7f439bdd31c901c802108ec903a3bfc0448c3d1' in submodule path 'vendor/brightray'
Unable to checkout 'b1d7464f1c05456027d41fa97384765bc1790212' in submodule path 'vendor/node'

Traceback (most recent call last):
  File "./script/bootstrap.py", line 119, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 23, in main
    update_submodules()
  File "./script/bootstrap.py", line 53, in update_submodules
    execute(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/Users/brandon.craig/Code/atom-shell/script/lib/util.py", line 142, in execute
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```
