### ISSUE TITLE
ATOM_NODE_VERSION=0.15.9 headers unavailable, apm install fails

### ISSUE THREAD

**Issue by andymorris** [atom/atom-shell#1046]
I am trying to use a native node module in my atom-shell project, following the instructions in the docs. However, exporting `ATOM_NODE_VERSION=0.15.9` results in an HTTP 403 error while downloading the headers. Getting headers for 0.16.0 and other higher versions works, but I get the 403 for any 0.15.x versions. Full error message from `apm install .` is below.

Thanks for any help!

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | darwin | x64
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.15.9/node-v0.15.9.tar.gz
gyp http 403 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.15.9/node-v0.15.9.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: 403 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:1255:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1588:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:514:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:369:25)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.15.9" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/andy/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by zcbenz** [comment]
Before v0.16.0 we used Node's version for the headers, you can try using `ATOM_NODE_VERSION=0.11.13` for building.
