### ISSUE TITLE
Error on v0.21.0: Module version mismatch. Expected 41, got 17

### ISSUE THREAD

**Issue by reggi** [atom/atom-shell#1070]
I'm getting this error on the newest version of AtomShell v0.21.0

> A JavaScript error occured in the browser process

```javascript
Uncaught Exception:
Error: Module version mismatch. Expected 41, got 17.
    at Error (native)
    at Object.module.(anonymous function) [as .node] (/Users/thomas/Desktop/wallpaper/wallpaper-app/build/darwin/atom-shell/Holstee.app/Contents/Resources/atom/common/lib/asar.js:422:20)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/thomas/Desktop/wallpaper/wallpaper-app/build/darwin/atom-shell/Holstee.app/Contents/Resources/app/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/Users/thomas/Desktop/wallpaper/wallpaper-app/build/darwin/atom-shell/Holstee.app/Contents/Resources/app/node_modules/nslog/lib/nslog.js:15:4)
    at Module._compile (module.js:475:26)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/thomas/Desktop/wallpaper/wallpaper-app/build/darwin/atom-shell/Holstee.app/Contents/Resources/app/index.js:19:13)
    at Module._compile (module.js:475:26)
```

**Comment by reggi** [comment]
Updated `apm` and I'm having trouble rebuilding.

**Comment by reggi** [comment]
These errors actually point to an issue with [atom/node-nslog](https://github.com/atom/node-nslog) @zcbenz @kevinsawicki

**Comment by paulcbetts** [comment]
This means that you didn't rebuild native modules against the latest Atom Shell, or your apm was out-of-date. Try running `script/bootstrap` again

**Comment by zcbenz** [comment]
You have to rebuild native modules against atom-shell v0.21.0's headers, if you are using apm for building, you may want to upgrade apm to latest version, see also https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md.
