### ISSUE TITLE
.bootstrap.py crash on Windows 8.1 and Python 2.7.9

### ISSUE THREAD

**Issue by Trixt0r** [atom/atom-shell#1115]
I am still getting an error if i want to build Atom Shell on Windows 8.1 32-bit and Python 2.7.9.
Here is the log:
```
$ python script/bootstrap.py
Traceback (most recent call last):
  File "script\update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script\update-external-binaries.py", line 31, in main
    download_and_unzip('directxsdk')
  File "script\update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script\update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 48, in download
    web_file = urllib2.urlopen(url)
  File "c:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "c:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "c:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 50, in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 16, in main
    update_external_binaries()
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 22, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "c:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\Python27\\python.exe', 'script\\update-external-binaries.py']' returned non-zero exit status 1

Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 34, in main
    update_atom_shell()
  File "script/bootstrap.py", line 123, in update_atom_shell
    execute_stdout([sys.executable, update])
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 150, in execute_stdout
    execute(argv)
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 138, in execute
    raise e
subprocess.CalledProcessError: Command '['c:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\atom-shell\\script\\update.py']' returned non-zero exit status 1
```

**Comment by zcbenz** [comment]
It seems that GitHub Release always redirect the download url to S3 with `https` protocol, I'll turn off SSL verification to work around it.

**Comment by dentarg** [comment]
> It seems that GitHub Release always redirect the download url to S3 with https protocol, I'll turn off SSL verification to work around it.

Doesn't sound like good practice?
