### ISSUE TITLE
Bootstrapping fails

### ISSUE THREAD

**Issue by lllama** [atom/atom-shell#1156]
Running on Windows, though this doesn't seem like it should be specific to the platform:

```
[43]:> python .\bootstrap.py -v
Running in verbose mode
git submodule sync
Synchronizing submodule url for '../vendor/breakpad'
Synchronizing submodule url for '../vendor/brightray'
Synchronizing submodule url for '../vendor/depot_tools'
Synchronizing submodule url for '../vendor/native_mate'
Synchronizing submodule url for '../vendor/node'
git submodule update --init --recursive
fatal: reference is not a tree: e3a3fd45aa7f6c247d9e9ab0900164004294fc8d
fatal: reference is not a tree: a336a458016ced89aba90dfc3f4c8222ae3b1403
Unable to checkout 'e3a3fd45aa7f6c247d9e9ab0900164004294fc8d' in submodule path '../vendor/brightray/vendor/libchromiumcontent/vendor/depot_tools'
Unable to checkout 'a336a458016ced89aba90dfc3f4c8222ae3b1403' in submodule path '../vendor/brightray/vendor/libchromiumcontent/vendor/python-patch'
Failed to recurse into submodule path '../vendor/brightray/vendor/libchromiumcontent'
Failed to recurse into submodule path '../vendor/brightray'
None
Traceback (most recent call last):
  File ".\bootstrap.py", line 127, in <module>
    sys.exit(main())
  File ".\bootstrap.py", line 26, in main
    update_submodules()
  File ".\bootstrap.py", line 54, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Users\Felix Ingram\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```
Looks like the current submodule commit references no longer exist (seems to be the case for depot_tools at least)

**Comment by lllama** [comment]
This seems to have fixed itself. Only change I can think of is that I removed python33 from the path and replaced it with python27. Which doesn't really make sense (I was running the scripts with 2.7 regardless). Looks like build.py is now failing but I'll open a separate issue for that once I've looked at it some more.
