### ISSUE TITLE
fatal: reference is not a tree

### ISSUE THREAD

**Issue by gliurn** [atom/atom-shell#1255]
hi, i m testing an RPM package for Atom-shell, so i build atom-shell several times this morning (and it worked) but suddenly it have stopped working and i got this error while executing bootstrap.py:

fatal: reference is not a tree: 84b0897b6bf21d75ff03a1916513259aeb284252
Unable to checkout '84b0897b6bf21d75ff03a1916513259aeb284252' in submodule path 'vendor/brightray/vendor/libchromiumcontent'
Failed to recurse into submodule path 'vendor/brightray'

Traceback (most recent call last):
  File "./script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 26, in main
    update_submodules()
  File "./script/bootstrap.py", line 54, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/root/test2/atom-shell/script/lib/util.py", line 154, in execute_stdout
    execute(argv)
  File "/root/test2/atom-shell/script/lib/util.py", line 142, in execute
    raise e

i didnt reboot my machine or change any package but i ve seen you made commit at the same time so do you thnik it could come from you?

**Comment by zcbenz** [comment]
Sorry I accidentally updates the submodules, the master branch should work now.

**Comment by gliurn** [comment]
ty for the fast answer
