### ISSUE TITLE
Warn user of the right format if there is error when paring parameters

### ISSUE THREAD

**Issue by jwu** [atom/atom-shell#926]
I just found the error reports when sending Menu.popup( window, x, y ) with float point values. Here is the error message:

```
Uncaught Error: Error processing argument 1.
TypeError: Error processing argument 1.
    at TypeError (native)
    at Menu.popup (/Users/johnny/jwu/atom-test/Atom.app/Contents/Resources/atom/browser/api/lib/menu.js:115:19)
    at callFunction (/Users/johnny/jwu/atom-test/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:116:18)
    at EventEmitter.<anonymous> (/Users/johnny/jwu/atom-test/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:208:14)
    at EventEmitter.emit (events.js:118:17)
    at EventEmitter.<anonymous> (/Users/johnny/jwu/atom-test/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:118:17)
```

The error is caused by the following code: 

```js
menu.popup(Remote.getCurrentWindow(), 10.2, 10 );
```

To avoid this, I need to make sure the x, y be integer number before sending them to popup.

I think the low-level API should protect on this, and sending warning message to remind user in sending the right format.

**Comment by zcbenz** [comment]
In C++ there is no easy while portable way to get the type name of a type as String, so it is not practical to implement this. I'm closing this as won't fix.
